AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Environment:
    Type: String
  TableName:
    Type: String
  PartitionKey:
    Type: String
  SortKey:
    Type: String
  GSI:
    Type: String
  LSI:
    Type: String
Conditions:
  HasSortKey: !Not [!Equals [!Ref SortKey, ""]]
  HasGlobalSecondaryIndex: !Not [!Equals [!Ref GSI, ""]]
  HasLocalSecondaryIndex: !Not [!Equals [!Ref LSI, ""]]

Resources:
  # =========================================================================================
  # AWS DYNAMODB TABLE
  # ========================================================================================= 
  NewDynamoDBTable:
  Type: AWS::DynamoDB::Table
  Properties: 
    TableName: !Sub '${TableName}-${Environment}'
    BillingMode: PAY_PER_REQUEST
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    AttributeDefinitions:
      - AttributeName: !Ref PartitionKey
        AttributeType: S
      - !If 
        - HasSortKey
        - AttributeName: !Ref SortKey
          AttributeType: S
        - !Ref AWS::NoValue
    KeySchema:
      - AttributeName: !Ref PartitionKey
        KeyType: HASH
      - !If
        - HasSortKey
        - AttributeName: !Ref SortKey
          KeyType: RANGE
        - !Ref AWS::NoValue
    GlobalSecondaryIndexes:
      - !If 
        - HasGlobalSecondaryIndex
        - IndexName: !Sub '${TableName}-${Environment}-GSI'
          KeySchema:
            - AttributeName: !Ref GSI
              KeyType: HASH
        - !Ref AWS::NoValue
    LocalSecondaryIndexes:
      - !If
        - HasLocalSecondaryIndex
        - IndexName: !Sub '${TableName}-${Environment}-LSI'
          KeySchema:
            - AttributeName: !Ref LSI
              KeyType: HASH
        - !Ref AWS::NoValue