AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Environment:
    Type: String
  Repo:
    Type: String

Resources:
  # =========================================================================================
  # AWS IAM ROLE
  # ========================================================================================= 
  ExcutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-${AWS::StackName}-Fargate-Execution-Role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
            - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-${AWS::StackName}-Fargate-Task-Role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
            - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 1024
      Memory: 8192
      Family: !Sub '${Environment}-${AWS::StackName}-${Repo}-DynamoDB-Runner'
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: ECR_REPO
          Image: 012345678910.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:latest
      LogConfiguration:
        LogDriver: awslogs
        Options:
          awslogs-stream-prefix: !Sub '${Environment}-${AWS:StackName}'
          awslogs-group: !Sub '${Environment}-${Repo}-LogGroup'
      Environment:
        - Name: LOGGING_LEVEL
          Value: INFO
        - Name: APP_NAME
          Value: !Ref Repo
        - Name: ENVIRONMENT
          Value: !Ref Environment