AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Environment:
    Type: String
  TableName:
    Type: String
  PartitionKey:
    Type: String
  LSI:
    Type: String

Resources:
  # =========================================================================================
  # AWS DYNAMODB TABLE
  # ========================================================================================= 
  NewDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Sub '${TableName}-${Environment}'
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions:
        - AttributeName: !Ref PartitionKey
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref PartitionKey
          KeyType: HASH
      LocalSecondaryIndexes:
        - IndexName: !Sub '${TableName}-${Environment}-${LSI}-LSI'
          KeySchema:
            - AttributeName: !Ref LSI
              KeyType: HASH
          Projection:
            ProjectionType: ALL